"""fix in user model - add relationship

Revision ID: 03a75b2eba1b
Revises: fb6c83486f3a
Create Date: 2026-03-22 12:59:20.617344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a75b2eba1b'
down_revision = 'fb6c83486f3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
