"""change login column name to email_login

Revision ID: 1df1a55d12b5
Revises: 9970c0e560ec
Create Date: 2026-03-10 21:57:22.790886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df1a55d12b5'
down_revision = '9970c0e560ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_login', sa.String(length=50), nullable=False))
    op.drop_constraint('users_login_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email_login'])
    op.drop_column('users', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_login_key', 'users', ['login'])
    op.drop_column('users', 'email_login')
    # ### end Alembic commands ###
