"""divide username(user model) and email(profile model)

Revision ID: 1f4debf7c11e
Revises: a9fb7218878c
Create Date: 2026-03-10 22:34:41.063020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4debf7c11e'
down_revision = 'a9fb7218878c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_constraint('unique_email', 'users', type_='unique')
    op.create_unique_constraint('unique_username', 'users', ['username'])
    op.drop_column('users', 'email_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_login', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint('unique_username', 'users', type_='unique')
    op.create_unique_constraint('unique_email', 'users', ['email_login'])
    op.drop_column('users', 'username')
    op.drop_column('profiles', 'email')
    # ### end Alembic commands ###
