"""add nullable=True constraint to Document model attribute project_id

Revision ID: 47635f52e24b
Revises: 9bf79869702a
Create Date: 2026-03-26 21:10:06.896496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47635f52e24b'
down_revision = '9bf79869702a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
