"""change tablename of UserProject model from user_projects to users_projects(typo)

Revision ID: 5507759a42c0
Revises: ec8532ac03b2
Create Date: 2026-03-16 16:41:01.672711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5507759a42c0'
down_revision = 'ec8532ac03b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_projects',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('participant', name='projectrole', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.drop_table('user_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_projects',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('participant', name='projectrole'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='user_projects_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_projects_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', name='user_projects_pkey')
    )
    op.drop_table('users_projects')
    # ### end Alembic commands ###
