"""add name to owner_id ForeignKey constraint

Revision ID: 8099e858b1bc
Revises: fe70492f1484
Create Date: 2026-03-13 12:47:12.907618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8099e858b1bc'
down_revision = 'fe70492f1484'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('fk_projects_owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('projects_owner_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['fk_projects_owner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('projects', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_owner_id_fkey', 'projects', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.drop_column('projects', 'fk_projects_owner_id')
    # ### end Alembic commands ###
