"""add to_delete attribute to file model

Revision ID: 82d510f2bdb3
Revises: 03a75b2eba1b
Create Date: 2026-03-24 15:04:32.303470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82d510f2bdb3'
down_revision = '03a75b2eba1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('to_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'to_delete')
    # ### end Alembic commands ###
