"""add general use field in files model

Revision ID: a6c9c91dc779
Revises: cb5f3ee375db
Create Date: 2026-03-22 12:34:12.708137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c9c91dc779'
down_revision = 'cb5f3ee375db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('general_purpose', sa.Boolean(), nullable=True))
    op.drop_column('files', 'update_allowed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('update_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('files', 'general_purpose')
    # ### end Alembic commands ###
