"""create name for unique constraint

Revision ID: a9fb7218878c
Revises: 1df1a55d12b5
Create Date: 2026-03-10 22:19:41.573685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fb7218878c'
down_revision = '1df1a55d12b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_login_key', 'users', type_='unique')
    op.create_unique_constraint('unique_email', 'users', ['email_login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_email', 'users', type_='unique')
    op.create_unique_constraint('users_email_login_key', 'users', ['email_login'])
    # ### end Alembic commands ###
