"""add foreign key to project model '[ProjectDocument.project_id]'

Revision ID: ad74ebd06c72
Revises: a6c9c91dc779
Create Date: 2026-03-22 12:46:49.059892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad74ebd06c72'
down_revision = 'a6c9c91dc779'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
