"""change TIMESTAMP to DateTime and add created_at and updated_at fields to project model

Revision ID: b503ca222133
Revises: cb7d2b959110
Create Date: 2026-03-16 16:33:15.319318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b503ca222133'
down_revision = 'cb7d2b959110'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'updated_at')
    op.drop_column('projects', 'created_at')
    # ### end Alembic commands ###
