"""replace name and surname by first_name and last_name + add new constraints for length of these fields

Revision ID: cb7d2b959110
Revises: 8099e858b1bc
Create Date: 2026-03-16 10:59:13.511865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7d2b959110'
down_revision = '8099e858b1bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.drop_column('profiles', 'surname')
    op.drop_column('profiles', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('surname', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'last_name')
    op.drop_column('profiles', 'first_name')
    # ### end Alembic commands ###
