"""add cascade delete constaint to user vs profile

Revision ID: d01a6e607132
Revises: 1f4debf7c11e
Create Date: 2026-03-11 11:11:31.087808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01a6e607132'
down_revision = '1f4debf7c11e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
