"""add storage_used_bytes attr to project model

Revision ID: e089ff65c9c8
Revises: 47635f52e24b
Create Date: 2026-03-30 15:39:00.679613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e089ff65c9c8'
down_revision = '47635f52e24b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_project_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['id'])
    op.add_column('projects', sa.Column('storage_used_bytes', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'storage_used_bytes')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_project_id_fkey', 'documents', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
