"""add unique constraint to email field in Profile model

Revision ID: ec8532ac03b2
Revises: b503ca222133
Create Date: 2026-03-16 16:37:25.259879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8532ac03b2'
down_revision = 'b503ca222133'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profiles', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    # ### end Alembic commands ###
