"""delete unusefull relationship note fron Project model

Revision ID: fb6c83486f3a
Revises: ad74ebd06c72
Create Date: 2026-03-22 12:54:42.532971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb6c83486f3a'
down_revision = 'ad74ebd06c72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
